alias ls='ls -1 --color=auto'
alias reboot='sudo reboot'
alias poweroff='sudo poweroff'
alias shutdown='sudo shutdown'
alias bandkar='xset dpms force off'
alias sl='ls -l --color=auto'
alias ll='ls -hlt --color=auto'
alias la='ls -ahlt --color=auto'
alias pdflatex='pdflatex --interaction batchmode'
alias vim='vim -p '
alias vimo='vim -O '
alias v=vim
alias more='less'
alias wget='wget -c '
alias screens='screen -ls'
alias screenS='screen -S'
alias echo='echo -e '
alias clipboard='xclip -selection "clipboard" -o'
alias ..='cd ..'
alias ...='cd ../..'
alias ....=' cd ../../..'
alias xc='xclip -selection clipboard -i '
alias ports='netstat -tlnp | column -t '
alias xo='xdg-open '
alias df='df -h '
alias py='python '
alias repoUpdate='repo checkout stage && repo forall -c "git remote update && git pull origin stage"'
alias gut='git'
alias cd..='cd ..'
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias rm=\rm
