# ~/.tmux/dark.conf
set -g status-bg '#282828'
set -g status-fg '#ebdbb2'
set -g status-left '#[fg=#282828, bg=#fabd2f] #H #[fg=#ebdbb2, bg=#504945] #S #[fg=#ebdbb2, bg=#282828]'
set -g status-right "#[fg=#ebdbb2, bg=#504945] #(free -h | awk '/^Mem/ {print $4\"/\"$2}') #[fg=#282828, bg=#fabd2f] %a,%d %b %H:%M "
set -g status-style "bg=#282828,fg=#ebdbb2"
set -g window-status-style "fg=#a89984,bg=#282828"
set -g window-status-current-style "fg=#ebdbb2,bg=#282828,bold"

