## Globals ##
set -g allow-passthrough on
set -g set-clipboard on
set -g update-environment "APPEARANCE"
set -g default-terminal "tmux-256color"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'
set -as terminal-overrides ',*:Ms=\E]52;%p1%s;%p2%s\007'
set -g history-limit 8196
set -g mouse off
set -g repeat-time 300
set -s escape-time 0

# Set prefix key to Ctrl-j
unbind-key C-b
set-option -g prefix C-j
bind C-k send-prefix

# Window nav
set -g base-index 1
setw -g pane-base-index 1
bind C-j last-window
bind c new-window -c '#{pane_current_path}'
bind M-c new-window -c '#{pane_current_path}'
bind N swap-window -s . -t %%
bind S command-prompt "rename-session %%"
bind r source-file ~/.tmux.conf

# Copy-Paste
setw -g mode-keys vi
bind -n M-Space copy-mode
bind -n M-p paste-buffer
bind -T copy-mode-vi Escape send-keys -X cancel
bind -T copy-mode-vi Space  send-keys -X begin-selection
bind -T copy-mode-vi y      send-keys -X copy-selection-no-clear
bind -T copy-mode-vi Enter  send-keys -X copy-selection-and-cancel

# command/message line colors
# set -g message-fg white
# set -g message-bg black
# set -g message-attr bright

# Terminal emulator window title
set -g set-titles on
set -g set-titles-string '#h: #S: #W'

# Status Bar
set -g status-interval 10
set -g status-justify left
set -g status-left-length 70

# Default to light
source-file ~/.tmux/dark.conf
set-environment -g THEME dark
set-environment -g APPEARANCE dark

bind T if-shell "tmux show-environment -g THEME | grep -q dark" \
  "source-file ~/.tmux/light.conf; set-environment -g THEME light; set-environment -g APPEARANCE light" \
  "source-file ~/.tmux/dark.conf; set-environment -g THEME dark; set-environment -g APPEARANCE dark"

## WINDOWS ##
# Window behavior
# setw -g utf8 on
setw -g allow-rename on
setw -g automatic-rename on
setw -g automatic-rename-format '#{?#{==:#{pane_current_command},zsh},#{b:pane_current_path},#{pane_current_command}}'

bind A command-prompt "rename-window %%; setw automatic-rename off"
bind a setw automatic-rename on
bind N command-prompt "swap-window -t %%"
bind m command-prompt -p "Monitor silence for (seconds):" "setw monitor-silence %%"
unbind !
bind ! command-prompt -p "Monitor activity (on|off):" "setw monitor-activity %%"

# det window title colors
setw -g window-status-format " #F#I #W "

# active window title colors
# setw -g window-status-current-attr bold
setw -g window-status-current-format " #F#I #W "


## PANES ##
set -g pane-border-style fg=colour238
set -g pane-active-border-style fg=blue

# For splitting horizontally/vertically
bind _ split-window -v -c '#{pane_current_path}'
bind | split-window -h -c '#{pane_current_path}'

# Pane navigation
bind -r j select-pane -D
bind -r k select-pane -U
bind -r h select-pane -L
bind -r l select-pane -R

# Pane resizing
bind -r +   resize-pane -U
bind -r -   resize-pane -D
bind -r <   resize-pane -L
bind -r >   resize-pane -R
bind -r K   resize-pane -U 5
bind -r J   resize-pane -D 5
bind -r H   resize-pane -L 5
bind -r L   resize-pane -R 5

# 30:70 layout (left pane 30%, right pane 70%)
bind M-= select-layout even-horizontal \; resize-pane -t 1 -x 30%
